### ISSUE TITLE
Support existing teamproject in AzureDevOps to create Git Repos

### ISSUE THREAD

**Issue by LucaSantopadre** [krateoplatformops/azuredevops-provider#1]
Support for existing project during creation of GitRepos.

PROBLEM
Actually we need to create first resource of type TeamProject, with a project name that doesn't exist in Azure DevOps, and then we able to create Git Repos in this project.
If a project name alredy exist we receive error status in conditions on TeamProject resource.

example
```
status:
    conditions:
    - lastTransitionTime: "2023-02-24T13:45:59Z"
      reason: Creating
      status: "False"
      type: Ready
    - lastTransitionTime: "2023-02-24T13:45:59Z"
      message: 'create failed: unexpected status: 400: azuredevops: TF200019: The
        following project already exists on the Azure DevOps Server: <name>. You
        cannot create a new project with the same name as an existing project. Provide
        a different name. (ProjectAlreadyExistsException, 3000)'
```

REQUEST
Able to create Git Repos in existing Azure DevOps Projects.
