### ISSUE TITLE
Missing `nil` handling in "Run" controller

### ISSUE THREAD

**Issue by matteogastaldello** [krateoplatformops/azuredevops-provider#104]
**Describe the bug**
When creating a Run resource, the azure devops controller pod crashes reporting error in image below

The error occurs because of `spec.resources` is missing in the Run CR 

```yaml
deletionPolicy: Orphan
  connectorConfigRef:
    namespace: krateo-system
    name: connectorconfig-sample
  pipelineRef:
    name: "krateotesttopic-pipeline-confluent-topic-creation"
    namespace: krateo-system
  runParameters:
    previewRun: false 
    templateParameters:
      debug: "true"
      cTopic: "true"
      cSA: "false"
      cACLS: "false"
      env: dev
      serviceaccount: null
      project: Platform
      topic_name: krateotesttopic
      topic_partition: "1"
      acls: null
```

![Image1](https://github.com/user-attachments/assets/06a752e4-8dca-47ea-8e13-a79e8ab17c43)
