### ISSUE TITLE
GitRepository points to the wrong TeamProject if the projectRef is not being previously created

### ISSUE THREAD

**Issue by braghettos** [krateoplatformops/azuredevops-provider#12]
**Describe the bug**
Two concurrent situations must occur to trigger this bug: 
1. a GitRepository manifest is trying to create a repository with a name that already exists in another project
2. the same GitRepository manifest is pointing to a _projectRef_ that is not yet being created when the GitRepository manifest is applied.

**To Reproduce**
1. Apply the following manifest:

```
apiVersion: azuredevops.krateo.io/v1alpha1
kind: ConnectorConfig
metadata:
  name: connectorconfig-sample
  annotations:
    krateo.io/connector-verbose: "false"
spec:
  apiUrl: https://dev.azure.com
  credentials:
    secretRef:
      namespace: krateo-system
      name: azuredevops-endpoint
      key: token
---
apiVersion: azuredevops.krateo.io/v1alpha1
kind: TeamProject
metadata:
  name: teamproject-sample1
  annotations:
    krateo.io/connector-verbose: "false"
spec:
  name: teamproject-sample1
  organization: krateo
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit olè
  visibility: private
  capabilities:
    versioncontrol:
      sourceControlType: Git
    processTemplate:
      templateTypeId: 6b724908-ef14-45cf-84f8-768b5384da45
  connectorConfigRef:
    namespace: krateo-system
    name: connectorconfig-sample
---
apiVersion: azuredevops.krateo.io/v1alpha1
kind: GitRepository
metadata:
  name: gitrepository-sample1
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  name: gitrepository-sample
  initialize: true
  projectRef:
    name: teamproject-sample1
    namespace: krateo-system
  connectorConfigRef:
    namespace: krateo-system
    name: connectorconfig-sample

```
2. Check that the CR GitRepository _gitrepository-sample1_ is correctly pointing to the right URL:

```
kubectl get gitrepository

NAME                    REMOTE_URL                                                                          READY
gitrepository-sample1   https://krateo@dev.azure.com/krateo/teamproject-sample1/_git/gitrepository-sample   True
```

3. Apply the following manifest:

```
apiVersion: azuredevops.krateo.io/v1alpha1
kind: TeamProject
metadata:
  name: teamproject-sample2
  annotations:
    krateo.io/connector-verbose: "false"
spec:
  name: teamproject-sample2
  organization: krateo
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit olè
  visibility: private
  capabilities:
    versioncontrol:
      sourceControlType: Git
    processTemplate:
      templateTypeId: 6b724908-ef14-45cf-84f8-768b5384da45
  connectorConfigRef:
    namespace: krateo-system
    name: connectorconfig-sample
---
apiVersion: azuredevops.krateo.io/v1alpha1
kind: GitRepository
metadata:
  name: gitrepository-sample2
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  name: gitrepository-sample
  initialize: true
  projectRef:
    name: teamproject-sample2
    namespace: krateo-system
  connectorConfigRef:
    namespace: krateo-system
    name: connectorconfig-sample
```

5. Check that the CR GitRepository _gitrepository-sample2_ is pointing to the wrong URL (actually, the remoteUrl of the previous repository):

```
kubectl get gitrepository   

NAME                    REMOTE_URL                                                                          READY
gitrepository-sample1   https://krateo@dev.azure.com/krateo/teamproject-sample1/_git/gitrepository-sample   True
gitrepository-sample2   https://krateo@dev.azure.com/krateo/teamproject-sample1/_git/gitrepository-sample   True

```
7. After a while, once also the second TeamProject is being created, the _REMOTE_URL_ of the _gitrepository-sample2_ is correctly updated:

```
kubectl get gitrepository 

NAME                    REMOTE_URL                                                                          READY
gitrepository-sample1   https://krateo@dev.azure.com/krateo/teamproject-sample1/_git/gitrepository-sample   True
gitrepository-sample2   https://krateo@dev.azure.com/krateo/teamproject-sample2/_git/gitrepository-sample   True
```

**Expected behavior**
I expect that the _gitrepository-sample2_ points to the right _teamproject_

**Additional context**
After digging in the logs, I found that the following request is made:

GET /krateo/_apis/git/repositories?api-version=7.0&includeHidden=true HTTP/1.1

I think that in the response payload the operator already finds a repository with the same name and it takes the remoteUrl of the wrong repository.
[azuredevops-provider-logs.txt](https://github.com/krateoplatformops/azuredevops-provider/files/12052299/azuredevops-provider-logs.txt)
