### ISSUE TITLE
New Pipeline Object is not correctly created on Azure Devops

### ISSUE THREAD

**Issue by jacopoberta** [krateoplatformops/azuredevops-provider#14]
**Describe the bug**
When a new object of kind "Pipeline" is processed by the provider, the pipeline created on Azure Devops portal is not working correctly: the triggers of the pipeline are not registered. In order to fix this, I found the following threads on stackoverflow
https://stackoverflow.com/questions/70849510/azure-devops-rest-api-created-pipeline-will-not-trigger
https://stackoverflow.com/questions/59853889/how-to-create-new-build-pipeline-using-azure-devops-rest-api

**To Reproduce**
1. create a new pipeline object with the following k8s manifest 
```
apiVersion: azuredevops.krateo.io/v1alpha1
kind: Pipeline
  name: pipeline-ci
spec:
  configurationType: yaml
  connectorConfigRef:
    name: connectorconfig
    namespace: krateo-system
  definitionPath: /path/to/pipeline.yaml
  deletionPolicy: Delete
  folder: guardian-il
  name: guardian-il-CI
  projectRef:
    name: teamproject
    namespace: krateo-system
  repositoryRef:
    name: gitrepository
    namespace: krateo-system
  repositoryType: azureReposGit
```

and the following azure pipeline pipeline source code:

```
appendCommitMessageToRunName: false
trigger: none
pool:
  vmImage: 'ubuntu-latest'
resources:
  repositories:
  - repository: sdd-infra
    type: git
    name: sdd-infra
    trigger:
    - dev
    - tst
    - uat
    - pro
stages: xxx
```

**Expected behavior**
The pipeline will automatically triggered when developers push code on target git repositories
