### ISSUE TITLE
CR User doesn't update membership to groups

### ISSUE THREAD

**Issue by jacopoberta** [krateoplatformops/azuredevops-provider#56]
**Describe the bug**
When a new User CR is created and the annotation "krateo.io/management-policy: observe-update" is setup, even if the spec.groupRefs array is filled, the ADO User is not updated and not inserted into the ADO groups placed in the array.
If the annotation "krateo.io/management-policy: observe-update" is removed, a brand new user is always created on ADO (even if there is an existing ADO user with the exactly same name).

**To Reproduce**
use the following yaml to reproduce

```yaml
apiVersion: azuredevops.krateo.io/v1alpha1
kind: Users
metadata:
  annotations:
    krateo.io/connector-verbose: 'false'
    krateo.io/management-policy: observe-update
  name: test-user
spec:
  connectorConfigRef:
    name: ga-0326-3-connectorconfig-gruppoapplicativo
    namespace: default
  deletionPolicy: Delete
  groupRefs:
    - name: ref-to-group-1
      namespace: krateo-system
    - name: ref-to-group-2
      namespace: krateo-system
  organization: krateo-sandbox-tst
  user:
    name: project-name Build Service (krateo-sandbox-tst)
```
