### ISSUE TITLE
Team CRs crash loop on provider

### ISSUE THREAD

**Issue by jacopoberta** [krateoplatformops/azuredevops-provider#59]
**Describe the bug**
Only in production environment, Team CR make the azuredevops provider to crash. In other env, this issue is not present. The differences between pro env and other envs is related to organization settings.

Please refere to the log to get further information (the Team is created on Azure Devops, but it's not added to any group)

The Team CR is like the following

```yaml
apiVersion: azuredevops.krateo.io/v1alpha1
kind: Team
metadata:
  name: bse-canali-team-gruppo-developers
spec:
  connectorConfigRef:
    name: bse-canali-connectorconfig-gruppoapplicativo
    namespace: default
  deletionPolicy: Orphan
  description: Team created by Krateo
  groupRefs:
    - name: bse-canali-group-developers-gruppo-applicativo
      namespace: krateo-system
  name: bse-canali-Developers
  projectRef:
    name: bse-canali-teamproject-gruppoapplicativo
    namespace: krateo-system
```
