### ISSUE TITLE
CR Endpoint is not shared across AZD projects

### ISSUE THREAD

**Issue by jacopoberta** [krateoplatformops/azuredevops-provider#62]
**Describe the bug**
When a Endpoint CR is created with 'isShared' flag set to True and the 'serviceEndpointProjectReferences' array populated, the provider doesn't share the CR across projects.
Based on the logs, it first makes a GET call to

GET /{{organization}}/{{project}}s/_apis/serviceendpoint/endpoints?api-version=7.0&endpointNames={{endpoint.name}}includeFailed=false HTTP/1.1

If the GET request returns a valid response, the provider stop the reconciliation with success, without checking if the result is already shared across the desired projects placed in serviceEndpointProjectReferences array.

**To Reproduce**
create a CR like the following template. The DevOps_TO_ACR_BSE-PRO-NPCI-KRATEO-001 Endpoint must be present on the bse-backbone-teamproject-gruppoapplicativo-bsetoolchaindevops project and not shared with the bse-backbone-teamproject-gruppoapplicativo project.

```yaml

apiVersion: azuredevops.krateo.io/v1alpha1
kind: Endpoint
metadata:
  annotations:
    krateo.io/connector-verbose: 'true'
    krateo.io/management-policy: observe-create-update
    krateo.io/paused: 'false'
  name: test-jb
spec:
  connectorConfigRef:
    name: bse-backbone-connectorconfig-gruppoapplicativo
    namespace: krateo-system
  deletionPolicy: Orphan
  name: DevOps_TO_ACR_BSE-PRO-NPCI-KRATEO-001
  isShared: true
  projectRef:
    name: bse-backbone-teamproject-gruppoapplicativo-bsetoolchaindevops
    namespace: krateo-system
  serviceEndpointProjectReferences:
    - description: aaaa sharing service connection for Registry
      name: DevOps_TO_ACR_BSE-PRO-NPCI-KRATEO-001
      projectRef:
        name: bse-backbone-teamproject-gruppoapplicativo
        namespace: krateo-system

```

**Expected behavior**
After the GET request to GET /{{organization}}/{{project}}s/_apis/serviceendpoint/endpoints?api-version=7.0&endpointNames={{endpoint.name}}includeFailed=false HTTP/1.1, the provider must check if serviceEndpointProjectReferences items are already present in the serviceEndpointProjectReferences response array.
If one or more projects are not present, a new API call must be triggered in order to share the Endpoint across the missing projects.
