### ISSUE TITLE
Unable to delete TeamProject if ConnectorConfig has been previously removed

### ISSUE THREAD

**Issue by braghettos** [krateoplatformops/azuredevops-provider#8]
**Describe the bug**
If the ConnectorConfig resource has been deleted before the TeamProject resource, then the latter cannot be deleted:

```
status:
  conditions:
  - lastTransitionTime: "2023-05-09T13:18:31Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-05-09T13:26:40Z"
    message: 'connect failed: cannot get diego-troubleshooting-1 connector config:
      ConnectorConfig.azuredevops.krateo.io "diego-troubleshooting-1" not found'
    reason: ReconcileError
    status: "False"
    type: Synced
```

**To Reproduce**
1. 
```
kubectl apply -f - <<EOF
apiVersion: azuredevops.krateo.io/v1alpha1
kind: ConnectorConfig
metadata:
  name: diego-troubleshooting-1
spec:
  apiUrl: https://dev.azure.com
  credentials:
    secretRef:
      key: token
      name: azuredevops-endpoint
      namespace: krateo-system
---
apiVersion: azuredevops.krateo.io/v1alpha1
kind: TeamProject
metadata:
  annotations:
    krateo.io/connector-verbose: "true"
  name: diego-troubleshooting-1
spec:
  capabilities:
    processTemplate:
      templateTypeId: 6b724908-ef14-45cf-84f8-768b5384da45
    versioncontrol:
      sourceControlType: Git
  connectorConfigRef:
    name: diego-troubleshooting-1
    namespace: krateo-system
  deletionPolicy: Delete
  name: diego-troubleshooting-1
  organization: Kiratech-BancaSella
EOF
```

2. 
```
kubectl delete -f - <<EOF
apiVersion: azuredevops.krateo.io/v1alpha1
kind: ConnectorConfig
metadata:
  name: diego-troubleshooting-1
spec:
  apiUrl: https://dev.azure.com
  credentials:
    secretRef:
      key: token
      name: azuredevops-endpoint
      namespace: krateo-system
---
apiVersion: azuredevops.krateo.io/v1alpha1
kind: TeamProject
metadata:
  annotations:
    krateo.io/connector-verbose: "true"
  name: diego-troubleshooting-1
spec:
  capabilities:
    processTemplate:
      templateTypeId: 6b724908-ef14-45cf-84f8-768b5384da45
    versioncontrol:
      sourceControlType: Git
  connectorConfigRef:
    name: diego-troubleshooting-1
    namespace: krateo-system
  deletionPolicy: Delete
  name: diego-troubleshooting-1
  organization: Kiratech-BancaSella
EOF
```

**Expected behavior**
`ConnectorConfig` shouldn't be deleted before any resource that depends on it. 

**Additional context**
A possible solution could be adding a `ownerReference` to the `ConnectorConfig` resource: https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications
